// Generated by scripts/import-cohort-csv.mjs — do not edit by hand.
// Re-run the importer against the intake sheet to refresh this file.
//
// Public profile fields only. The source sheet also holds dates of birth, phone
// numbers and personal email addresses; none of that is imported, and none of
// it belongs on a public page.

import type { CohortMember } from "@/lib/cohorts";

export const firstYearRoster: CohortMember[] = [
    {
        name: "Aadishree Joshi",
        github: "aadishree",
    },
    {
        name: "AAYUSH RAJ",
        github: "Aayush-Raj07022008",
        linkedin: "https://www.linkedin.com/in/aayush-raj-051681374",
    },
    {
        name: "Abhirup Karmakar",
        github: "AbhirupKarmakar",
    },
    {
        name: "Abhishek Raj Verma",
        github: "abhishekrajv7-cmd",
        linkedin: "https://www.linkedin.com/feed/",
        website: "https://qvic.in/",
    },
    {
        name: "Adhithya Pandiri",
        github: "adhithyapandiri-a11y",
        linkedin: "https://www.linkedin.com/in/adhithyapandiri",
    },
    {
        name: "Adithya Ramesh",
        github: "adithya12ramesh",
        linkedin: "https://www.linkedin.com/in/adithya-ramesh-6b5761421",
    },
    {
        name: "Aditya Goyal",
        github: "goyaladitay11",
    },
    {
        name: "Aditya Jha",
        github: "aditya-jha-develops",
        linkedin: "https://linkedin.com/in/aditya-develops/",
        website: "https://aditya-develops.vercel.app/",
    },
    {
        name: "Aditya mishra",
        github: "adityamishra-cell",
        linkedin: "https://www.linkedin.com/in/aditya-rl/",
    },
    {
        name: "Aditya Tulo",
        github: "Psychoriz",
    },
    {
        name: "Akash Ramanathan Iyer",
        github: "akash-iyer-27",
    },
    {
        name: "Akshat Chauhan",
        github: "Akshat698",
    },
    {
        name: "Akshat P S Bhadauria",
        github: "akshh-bot",
        linkedin: "https://www.linkedin.com/in/akshat-pratap-singh-933301423?utm_source=share_via&utm_content=profile&utm_medium=member_ios",
    },
    {
        name: "Akshat Singh",
        github: "akshatsingh202007-ui",
        linkedin: "https://www.linkedin.com/in/akshat-singh-ba7a9127b?utm_source=share_via&utm_content=profile&utm_medium=member_android",
    },
    {
        name: "Aman",
        github: "shamkian0326-creator",
        linkedin: "https://www.linkedin.com/in/aman-singh-3731772a6",
    },
    {
        name: "Amartya Sen Badal",
        github: "theamartyasen",
        linkedin: "https://www.linkedin.com/in/theamartyasen",
    },
    {
        name: "Ananya Pathak",
        github: "ananyapathak-dev",
    },
    {
        name: "Anindita Das",
        github: "Anindita4505",
    },
    {
        name: "Anshika Indu",
        github: "Anshika-Indu",
        linkedin: "https://www.linkedin.com/in/anshika-indu-15-11-2008-anshika-indu/",
    },
    {
        name: "Anuj Preet",
        github: "spawne4",
        linkedin: "https://www.linkedin.com/in/anuj-preet-7b56b0421?utm_source=share_via&utm_content=profile&utm_medium=member_android",
    },
    {
        name: "Anurag",
        github: "anurrag983",
        linkedin: "https://www.linkedin.com/in/anurag-singh-42b89a314?utm_source=share_via&utm_content=profile&utm_medium=member_android",
    },
    {
        name: "Apurv Tiwari",
        github: "apurvtiwari15",
        linkedin: "https://www.linkedin.com/in/apurv-tiwari-3118b2430?utm_source=share_via&utm_content=profile&utm_medium=member_ios",
    },
    {
        name: "Archisman Pal",
        github: "archismanpal07",
        linkedin: "https://www.linkedin.com/in/archismanpal07",
    },
    {
        name: "Arjun Shukla",
        github: "ArjunShukla76",
        linkedin: "https://www.linkedin.com/in/arjun-shukla-18170b2a8?utm_source=share_via&utm_content=profile&utm_medium=member_android",
    },
    {
        name: "Armaan Saxena",
        github: "armaan247",
        linkedin: "https://www.linkedin.com/in/armaan-saxena-213870423?utm_source=share_via&utm_content=profile&utm_medium=member_android",
        website: "https://-/",
    },
    {
        name: "Arman Sohil Vadhvania",
        github: "armanvadhvania1",
    },
    {
        name: "Arnav Sharma",
        github: "arnavsharma294-png",
        linkedin: "https://www.linkedin.com/in/arnav-sharma-2677b1421",
    },
    {
        name: "Aruna Ramanathan Iyer",
        github: "aruna-iyer",
        linkedin: "https://www.linkedin.com/in/aruna-iyer/",
    },
    {
        name: "Aryan Dixit",
        github: "SuspiciousChip",
        linkedin: "https://www.linkedin.com/in/aryan-dixit-043789404?utm_source=share_via&utm_content=profile&utm_medium=member_android",
    },
    {
        name: "ARYAN SIROHI",
        github: "aryansirohi2121-coder",
    },
    {
        name: "Aryan verma",
        github: "aryangetsreal",
        linkedin: "https://www.linkedin.com/in/aryan-verma-257747418?trk=contact-info",
    },
    {
        name: "Ashvanth",
        github: "Ashvanth-gif",
        linkedin: "https://www.linkedin.com/in/ashvanth-gandham-969a35365/",
    },
    {
        name: "Atharva Tukaram Gavhane",
        github: "atgavhane96",
        linkedin: "https://www.linkedin.com/in/atharva-gavhane-a10872416",
    },
    {
        name: "Aviral Srivastava",
        github: "wannabeaviral",
    },
    {
        name: "Ayaan Kapoor",
        github: "Ayaan-20-11",
        linkedin: "https://www.linkedin.com/in/ayaan-kapoor-/",
    },
    {
        name: "Ayaan Khan",
        github: "Ayaan-khan01",
        linkedin: "https://www.linkedin.com/in/ayaan-khan-94b04a42b",
    },
    {
        name: "Ayush Khajuria",
        github: "ayush213",
    },
    {
        name: "Ayush kumar mahato",
        github: "Heisenbrick",
        linkedin: "https://www.linkedin.com/in/ayush-mahato-34a032391?utm_source=share_via&utm_content=profile&utm_medium=member_android",
    },
    {
        name: "AYUSHRAJ",
        github: "ayush882244-crypto",
        linkedin: "https://www.linkedin.com/in/ayush-raj-b7b3522b4",
    },
    {
        name: "B Aadarsh",
        github: "MassGethu",
        linkedin: "https://www.linkedin.com/in/aadarsh-b-54811a419/",
    },
    {
        name: "Bhavyarajsinh Bhemsinh Amala",
        github: "bhavyarajsinh1510",
        linkedin: "https://www.linkedin.com/in/bhavyaraj-amala-b92a0b421?utm_source=share_via&utm_content=profile&utm_medium=member_android",
    },
    {
        name: "BONTHU BALAJI",
        github: "BONTHUBALAJI",
    },
    {
        name: "Chanchal Agarwal",
        github: "chanchalagarwal3580",
        linkedin: "https://www.linkedin.com/in/chanhcal-agarwal-569616358/",
    },
    {
        name: "Darshil P Jain",
        github: "darshilved99-svg",
    },
    {
        name: "Dhairya Agrawal",
        github: "dhairyaagrawalcode",
        linkedin: "https://www.linkedin.com/in/dhairya-agrawal-102307341/",
        website: "https://dhairya-agrawal.vercel.app/",
    },
    {
        name: "Dhairya Dev Singh",
        github: "Dhairya-Dev-Singh",
        linkedin: "https://www.linkedin.com/in/dhairya-dev-singh-0a46973a4/",
    },
    {
        name: "DHARISA SAI VISHAL",
        github: "saivishaldharisa-web",
    },
    {
        name: "DILREET KAUR",
        github: "Dilreet168",
        linkedin: "https://www.linkedin.com/in/dilreet-kaur-36b38a431",
    },
    {
        name: "DIPIKA",
        github: "drathava847-beep",
    },
    {
        name: "divyansh Kushwaha",
        github: "divyanshkush437-source",
        linkedin: "https://www.linkedin.com/in/divyansh-kushwaha-1b8711336/",
    },
    {
        name: "Divyanshu singh",
        github: "divyanshu2000k",
        linkedin: "https://www.linkedin.com/in/divyanshu-singh-07669a3a7?utm_source=share_via&utm_content=profile&utm_medium=member_android",
    },
    {
        name: "Ejaz Ahamed Khan",
        github: "ejazahamed08",
        linkedin: "https://www.linkedin.com/in/ejaz-ahamed-3223a242b/",
    },
    {
        name: "Gandhi ansh ankitbhai",
        github: "anshgandhi68-sys",
        linkedin: "https://www.linkedin.com/in/ansh-a-gandhi-76257b420?utm_source=share_via&utm_content=profile&utm_medium=member_android",
    },
    {
        name: "Garv Sanveria",
        github: "garv-sanveria",
        linkedin: "https://www.linkedin.com/in/garv-sanveria-59813b380/",
    },
    {
        name: "H Nishanth Rao",
        github: "raonishanth2000-hub",
    },
    {
        name: "H S BHARATH SURYA",
        github: "satanonsteroids2024-zzz",
        website: "https://studyguard-ai.netlify.app/",
    },
    {
        name: "Hari Sri SasiVathana G",
        github: "harisrish2512-ht",
        linkedin: "https://www.linkedin.com/in/hari-sri-sasivathana-g-653126430",
    },
    {
        name: "Harsh Nahar",
        github: "harshnahar07hmn",
    },
    {
        name: "Harsh Pandey",
        github: "harshpandey729",
        linkedin: "https://www.linkedin.com/in/harsh-pandey-a9bab0427",
    },
    {
        name: "Harshit Kandpal",
        github: "Harshit-2208",
    },
    {
        name: "Harshit Raj",
        github: "harryX18",
    },
    {
        name: "Harshita Dhakad",
        github: "Harshita-max4484",
        linkedin: "https://www.linkedin.com/in/harshita-dhakad-b978a5422?utm_source=share_via&utm_content=profile&utm_medium=member_ios",
    },
    {
        name: "Het ukani",
        github: "Cyberhet",
    },
    {
        name: "Himanshu Giri",
        github: "girihimanshu540-prog",
        linkedin: "https://www.linkedin.com/in/himanshu-giri-5b3509414?utm_source=share_via&utm_content=profile&utm_medium=member_android",
    },
    {
        name: "Ishan Kumar",
        github: "ishan-one8",
    },
    {
        name: "Ishita Roy",
        github: "xishitaxx",
    },
    {
        name: "J Yashwanth Raj",
        github: "TheAstro1",
        linkedin: "https://linkedin.com/in/yashwanth-raj-06a891339",
    },
    {
        name: "Jarvis Jeason Jacob",
        github: "Jarvis-J-Jacob",
        linkedin: "https://www.linkedin.com/in/jarvis-jeason-jacob-213124419/",
    },
    {
        name: "Jayvir Jadeja",
        github: "jayvirjadeja008-gif",
    },
    {
        name: "JEEVAN BASAPPA BAGI",
        github: "jeevan1668",
        linkedin: "https://www.linkedin.com/in/jeevan-basappa-bagi-987938430/",
    },
    {
        name: "K Chethan Chowdhary",
        github: "chethanchowdharykantamneni-design",
        linkedin: "https://www.linkedin.com/in/chethan-chowdhary-kantamneni-628191375/",
    },
    {
        name: "K.Eshanth Reddy",
        github: "reddieshanth-cpu",
        linkedin: "https://www.linkedin.com/in/k-eshanth-reddy-643483421?utm_source=share_via&utm_content=profile&utm_medium=member_ios",
    },
    {
        name: "Kakul Kashyap Deka",
        github: "kakuldeka",
    },
    {
        name: "Kanishk Patel",
        github: "kanishk-codex",
        linkedin: "https://www.linkedin.com/in/kanishk-patel-717b29424",
    },
    {
        name: "Kartik Khandelwal",
        github: "Illtrapx",
        linkedin: "https://www.linkedin.com/in/kartik-khandelwal-a84a14252",
    },
    {
        name: "Kartik Yadav",
        github: "kartikyadav090607",
    },
    {
        name: "Kavin Rau",
        github: "vexital-05",
        linkedin: "https://www.linkedin.com/in/kavincodes/",
    },
    {
        name: "Kirtan Maulik Joshi",
        github: "ThatKJ",
        linkedin: "https://www.linkedin.com/in/kirtan-joshi2412/",
    },
    {
        name: "Konduru Lakshmi sai Praneethl",
        github: "SaiPraneeth63",
        linkedin: "https://www.linkedin.com/in/konduru-lakshmi-sai-praneeth-abba75382",
    },
    {
        name: "Kovid Jain",
        github: "kovidjain",
        linkedin: "https://www.linkedin.com/public-profile/settings/?trk=d_flagship3_profile_self_view_public_profile&lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base%3BN7LNtIxoTkaiHa8Bs6kR7g%3D%3D",
    },
    {
        name: "Krishna Chandan Pakki",
        github: "krishnachandanofficial-PRO",
    },
    {
        name: "KUNCHAM LASYA KRISHNA",
        github: "lasyakrishna",
    },
    {
        name: "Laltesh Chaudhary",
        github: "CrackerHacker451",
        linkedin: "https://www.linkedin.com/in/laltesh-chaudhary-031a032a7?utm_source=share_via&utm_content=profile&utm_medium=member_android",
    },
    {
        name: "Liza Dsouza",
        github: "Liz0511",
        linkedin: "https://www.linkedin.com/in/liza-dsouza-050b05399",
    },
    {
        name: "Manav Dugar",
        github: "ManavTheOG",
        linkedin: "https://www.linkedin.com/in/manav-dugar-39305a403/",
        website: "https://maxer-site.pagesmith.app/",
    },
    {
        name: "Manjushree Chabbi",
        github: "ManjushreeChabbi",
        linkedin: "https://www.linkedin.com/in/manjushree-chabbi-513b9837b/",
    },
    {
        name: "Mayank suthar",
        github: "Mayanksuthar07",
    },
    {
        name: "Mehul Pundir Negi",
        github: "MehulNegi",
        linkedin: "https://www.linkedin.com/in/mehul-negi/",
    },
    {
        name: "Mohit Krishna Prasad",
        github: "prasadmohitk-afk",
        linkedin: "https://www.linkedin.com/in/mohit-prasad-a340a2411?utm_source=share_via&utm_content=profile&utm_medium=member_android",
    },
    {
        name: "MOHIT KUMAR KOUSHIK",
        github: "DRAGON-LORD-MIO-MARASKA",
    },
    {
        name: "Musarafa Khatun",
        github: "musarafakhatun19",
        linkedin: "https://www.linkedin.com/in/musarafa-khatun-a73a63431?utm_source=share_via&utm_content=profile&utm_medium=member_ios",
    },
    {
        name: "Naincy Meravi",
        github: "aashimeravi8-cloud",
    },
    {
        name: "Neeraj Kumar Sahu",
        github: "NeerajSahu2008",
    },
    {
        name: "Nikhil Aryan",
        github: "nikhilaryan6115-design",
        linkedin: "https://www.linkedin.com/in/nikhil-aryan-3ab8a7414/",
    },
    {
        name: "Nishpray Singh Thakur",
        github: "Nishpraysingh",
        linkedin: "https://www.linkedin.com/in/nishpray-singh-thakur-8a8865422",
    },
    {
        name: "Om Shukla",
        github: "omshukla1b",
        linkedin: "https://www.linkedin.com/in/om-shukla-2657b642b?utm_source=share_via&utm_content=profile&utm_medium=member_android",
    },
    {
        name: "Piushi sharma",
        github: "piushisharma04",
        linkedin: "https://www.linkedin.com/in/piushi-sharma-a67708431?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    },
    {
        name: "Prachi Darshi",
        github: "prachidarshi-2307",
        linkedin: "https://www.linkedin.com/in/prachi-darshi-540288405?utm_source=share_via&utm_content=profile&utm_medium=member_android",
    },
    {
        name: "Pranav Sankhyan",
        github: "Dev-Pranav-Sankhyan",
        linkedin: "https://www.linkedin.com/in/pranav-sankhyan-631bb3421",
    },
    {
        name: "Prantik Sarkar",
        github: "Prantik248",
    },
    {
        name: "Prathamesh Kanase",
        github: "kanaseprathamesh568-a11y",
    },
    {
        name: "Prince shamra",
        github: "PrinceCodes07-eng",
        linkedin: "https://www.linkedin.com/in/prince-sharma-56397a421?utm_source=share_via&utm_content=profile&utm_medium=member_android",
    },
    {
        name: "Prithvi Kumar Singh",
        github: "Prithvi-gif",
    },
    {
        name: "PUSHWANTH R REDDY",
        github: "thunder-pushu",
    },
    {
        name: "Raghav Sharma",
        github: "raghav-sharma-ai",
        linkedin: "https://www.linkedin.com/in/raghav-sharma-93288a414?utm_source=share_via&utm_content=profile&utm_medium=member_android",
    },
    {
        name: "Rajnish Pathak",
        github: "rajnishpathak-sketch",
        linkedin: "https://www.linkedin.com/in/rajnish-pathak-10304040b?utm_source=share_via&utm_content=profile&utm_medium=member_android",
    },
    {
        name: "Reva Bharol",
        github: "reva572",
        linkedin: "https://www.linkedin.com/in/reva-b-030734333/",
        website: "https://talksparapp-mm6cqzci.manus.space/",
    },
    {
        name: "Sabhya bhargava",
        github: "bhargavasabhya-lgtm",
    },
    {
        name: "Sagir Alam Sk",
        github: "SagirAlamSk",
    },
    {
        name: "saisasai veeraballe",
        github: "saiveera-007",
        linkedin: "https://www.linkedin.com/in/sai-veeraballe-1aaa16409",
    },
    {
        name: "Saksham Jaiswal",
        github: "saksham1319",
        linkedin: "https://www.linkedin.com/in/saksham6975?utm_source=share_via&utm_content=profile&utm_medium=member_android",
        website: "https://saksham1319.vercel.app/",
    },
    {
        name: "Samyak jain",
        github: "ritujain8638-source",
    },
    {
        name: "Sanjay Singh",
        github: "apsian4352-coder",
    },
    {
        name: "Shambhavi Sharma",
        github: "ShambhaviSharma28",
        linkedin: "https://www.linkedin.com/in/shambhavi-sharma-b73616377?utm_source=share_via&utm_content=profile&utm_medium=member_android",
    },
    {
        name: "Shikhar Kumar Prasad",
        github: "shikharprasad47",
    },
    {
        name: "Shivam Kumar",
        github: "Prince139-ai",
    },
    {
        name: "Shubhrodeep Sur",
        github: "Shubhroo21",
    },
    {
        name: "Sk Md Firdous",
        github: "skmdfirdousf34",
        linkedin: "https://www.linkedin.com/in/firdous-sk?utm_source=share_via&utm_content=profile&utm_medium=member_android",
        website: "https://skmdfirdous.vercel.app/",
    },
    {
        name: "sravan samudrala",
        github: "sravan793",
        linkedin: "https://www.linkedin.com/in/sravangupta-samudrala/",
    },
    {
        name: "Srija Sikly",
        github: "SrijaSikly",
    },
    {
        name: "Srishti",
        github: "srishti-thukran",
    },
    {
        name: "Sujal Jangde",
        github: "sujaljangde22",
        linkedin: "https://www.linkedin.com/in/sujal-jangde-4439753a6?utm_source=share_via&utm_content=profile&utm_medium=member_ios",
    },
    {
        name: "Sumit lal",
        github: "gavi2007",
        linkedin: "https://www.linkedin.com/in/sumit-lal-54b80331b/",
    },
    {
        name: "Swastik Katiyar",
        github: "swastikkatiyar",
    },
    {
        name: "Tejas Dharmendra Patel",
        github: "tdpatelgit",
        linkedin: "https://www.linkedin.com/in/tejas-dharmendra-patel-b37024362/",
    },
    {
        name: "Tejas Rastogi",
        github: "Tejasrastogi",
        linkedin: "https://www.linkedin.com/in/tejas-rastogi-21528a422?utm_source=share_via&utm_content=profile&utm_medium=member_ios",
    },
    {
        name: "Twinkle",
        github: "twi-ni",
        linkedin: "https://www.linkedin.com/in/twinkle-b67885430",
    },
    {
        name: "Ujjwal Dubey",
        github: "UjjwalDubey8810",
    },
    {
        name: "Umair Kadiroddin Shaikh",
        github: "umairkai",
        linkedin: "https://www.linkedin.com/in/umair-shaikh-33ab68240?utm_source=share_via&utm_content=profile&utm_medium=member_android",
    },
    {
        name: "Vaibhav Gupta",
        github: "vaibholuuu",
        linkedin: "https://www.linkedin.com/in/eggsgamemode/",
    },
    {
        name: "Vaibhvi",
        github: "vaibhvii",
        linkedin: "https://www.linkedin.com/in/vaibhvi-kataria-b1259a423?utm_source=share_via&utm_content=profile&utm_medium=member_android",
    },
    {
        name: "Vaishnavi choudhary",
        github: "mnivaishnavi-ctrl",
        linkedin: "https://www.linkedin.com/in/vaishnavi-choudhary-649ba7430?utm_source=share_via&utm_content=profile&utm_medium=member_android",
    },
    {
        name: "Vaishnavi Dhakwal",
        github: "vaishnavi-dwl",
    },
    {
        name: "Varun pateriya",
        github: "varunpateriya01",
        linkedin: "https://www.linkedin.com/in/varun-pateriya-60049842b?utm_source=share_via&utm_content=profile&utm_medium=member_android",
    },
    {
        name: "Vedant Saini",
        github: "vasux01",
    },
    {
        name: "Vedant Saware",
        github: "vedu-lab",
    },
    {
        name: "Venkata Vishaleswar Reddy kandula",
        github: "kvvishal7396",
        linkedin: "https://www.linkedin.com/in/venkata-vishaleswar-reddy-kandula-a4b2b442b?utm_source=share_via&utm_content=profile&utm_medium=member_android",
    },
    {
        name: "Vidyanshi Rajwadha",
        github: "VDISTHENEXT",
    },
    {
        name: "Vikas Shukla",
        github: "Vik755",
        linkedin: "https://www.linkedin.com/in/vikas-shukla-9a1880430?utm_source=share_via&utm_content=profile&utm_medium=member_ios",
    },
    {
        name: "Vinay Shambuling bichchali",
        github: "vinay34744",
        linkedin: "https://www.linkedin.com/in/vinay-bichali-1550ba275?utm_source=share_via&utm_content=profile&utm_medium=member_android",
    },
    {
        name: "Yash Panchal",
        github: "Yashpanchal8",
    },
];
